services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - '${NGINX_EXPOSED_80_PORT}:80'
      - '${NGINX_EXPOSED_443_PORT}:443'
      - '${BACKEND_EXPOSED_DEV_PORT}:${BACKEND_EXPOSED_DEV_PORT}'
      - '${FLOWER_EXPOSED_DEV_PORT}:${FLOWER_EXPOSED_DEV_PORT}'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
    env_file:
      - .env
    networks:
      - developmentnetwork


networks:
  developmentnetwork:
    name: backend_developmentnetwork
    external: true
