# Generated by Django 4.2.11 on 2024-12-03 23:45

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.new_ulid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('tweet_text', models.CharField(max_length=140)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tweet',
                'indexes': [models.Index(fields=['id'], name='Tweet_id_42b4d9_idx'), models.Index(fields=['created_by'], name='Tweet_created_df32cc_idx'), models.Index(fields=['-created_at'], name='Tweet_created_326920_idx')],
            },
        ),
    ]
