# Generated by Django 4.2.11 on 2024-12-03 23:45

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', core.fields.ULIDField(default=core.fields.new_ulid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('followee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Follow',
                'indexes': [models.Index(fields=['id'], name='Follow_id_336a13_idx'), models.Index(fields=['follower'], name='Follow_followe_f26d55_idx'), models.Index(fields=['followee'], name='Follow_followe_8ca957_idx')],
                'unique_together': {('follower', 'followee')},
            },
        ),
    ]
